language: perl
os:
  - linux
perl:
  - "5.28-thr"
  - "5.28"
  - "5.26-thr"
  - "5.26"
  - "5.24-thr"
  - "5.24"
  - "5.22-thr"
  - "5.22"
  - "5.20-thr"
  - "5.20"
  - "5.18-thr"
  - "5.18"
  - "5.16-thr"
  - "5.16"
  - "5.14-thr"
  - "5.14"
  - "5.12-thr"
  - "5.12"
  - "5.10-thr"
  - "5.10"
  - "5.8-thr"
  - "5.8"
env:
  - AUTOMATED_TESTING=1
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then perlbrew install-cpanm ; fi
install:
  - cpanm --quiet Test::More                        || true
  - cpanm --quiet Test::NoWarnings                  || true
notifications:
  irc:
    channels:
      - "irc.perl.org#csv"
    on_success: always
    on_failure: always
